import { initializeApp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";
import { getFirestore, collection, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig); const db=getFirestore(app);
const form=document.getElementById("registrationForm"), institution=document.getElementById("institution"), status=document.getElementById("status"), submitBtn=document.getElementById("submitBtn"), successBox=document.getElementById("successBox"), regNumber=document.getElementById("regNumber");
let institutions={universities:[],polytechnics:[]};
fetch("./institutions.json").then(r=>r.json()).then(d=>institutions=d).catch(()=>status.textContent="Could not load institution list. Refresh and try again.");
document.querySelectorAll('input[name="institutionType"]').forEach(r=>r.addEventListener("change",()=>{const list=r.value==="University"?institutions.universities:institutions.polytechnics; institution.disabled=false; institution.innerHTML='<option value="">Select your institution</option>'+list.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("");}));
function esc(v){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function createReg(){return `4REAL-${new Date().getFullYear()}-${Date.now().toString().slice(-7)}`;}
form.addEventListener("submit",async e=>{e.preventDefault();status.textContent="Submitting registration...";submitBtn.disabled=true;form.classList.add("loading");const type=document.querySelector('input[name="institutionType"]:checked')?.value||"";const applicant={firstName:document.getElementById("firstName").value.trim(),surname:document.getElementById("surname").value.trim(),email:document.getElementById("email").value.trim().toLowerCase(),phone:document.getElementById("phone").value.trim(),institutionType:type,institution:institution.value,department:document.getElementById("department").value.trim(),program:document.getElementById("program").value,previousStack:document.getElementById("stack").value,reason:document.getElementById("reason").value.trim(),registrationNumber:createReg(),status:"registered",createdAt:serverTimestamp()};try{await addDoc(collection(db,"registrations"),applicant);regNumber.textContent=applicant.registrationNumber;form.style.display="none";successBox.classList.add("show");}catch(err){console.error(err);status.textContent="Registration failed. Check your Firebase configuration and Firestore rules.";submitBtn.disabled=false;form.classList.remove("loading");}});
